name: Run code
on:
  push:
    branches:
      - dvc-pipeline
    paths:
    - config/**
    - src/**
    - data/*
    - .github/workflows/run_pipeline.yaml

jobs:
  dvc_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Install DVC
        run: |
          pip install dvc

      - name: Authenticate with Google Drive
        run: |
          echo ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }} > /tmp/google_drive_credentials.json
          dvc remote modify origin credential /tmp/google_drive_credentials.json

      - name: DVC pull
        run: |
          dvc pull
      - name: DVC repro
        run: |
          dvc repro
      - name: DVC push
        run: |
          dvc push
