name: CML Run

on: [push]

jobs:
  cml_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull DVC data
        run: |
          dvc pull --debug data

      - name: Reproduce DVC pipeline
        run: |
          dvc repro

      - name: Fetch master branch
        run: |
          git fetch --prune origin +refs/heads/master:refs/remotes/origin/master

      